### ISSUE TITLE
Add capability to adjust time/date for device

### ISSUE THREAD

**Issue by ionTomorrow** [EFForg/rayhunter#121]
On a device with an inactive SIM card the timestamps of captures are not helpful and start in 1969.

The capability to adjust the time & date will help users to correlate where they were when any particular event occurs.

**Comment by ionTomorrow** [comment]
I did insert an active SIM card today and confirmed the timestamp did get automatically updated. This would only work for carriers that also include time data, but I have been in countries where the carriers don't provide this.

**Comment by MatejKovacic** [comment]
Is it possible to set up NTP service? Also, NTS (Network Time Security) or NTP over HTTPS API would be dssirable, because I have seen some networks that are blocking NTP connections.

**Comment by wisxxx** [comment]
On an Orbic with an inactive SIM, timestamps are off about 17 seconds compared to my GPS watch and show EDT (GMT -4)

`"timestamp": "2025-03-11T11:43:51.588673853-04:00",`

However the "Date Started" and "Date of Last Message" show the correct (for me) time zone:

`Tue Mar 11 2025 08:43:50 GMT-0700 (Pacific Daylight Time)
`
If Rayhunter could somehow get time from a USB or WiFi client when a connection is established, that might be good enough. Or, a button on the Web UI that says "Set Time" might be a first step.

**Comment by jovimon** [comment]
I have the same issue, time is set to december 2020 every time I restart the device, in my case an Orbic with rayhunter v0.4.0.

I tried to use ADB and the rootshell installed by rayhunter to do a quick workaround, without success:

```
root@ubuntu:~# adb shell
/ $ date
Thu Dec 10 14:50:28 EST 2020
/ $ date -s "2025-06-29 12:32"
date: can't set date: Operation not permitted
Sun Jun 29 12:32:00 EDT 2025
/ $ /bin/rootshell 
bash-4.3# date
Thu Dec 10 14:50:41 EST 2020
bash-4.3# date -s "2025-06-29 12:32"
date: can't set date: Operation not permitted
Sun Jun 29 12:32:00 EDT 2025
bash-4.3# 
```

**Comment by untitaker** [comment]
This is also an issue with TP-Link. I think @wisxxx's suggestion makes the most sense:

* rayhunter stores a timedelta in memory, initialized with 0 at start.
* all timestamps rayhunter ever produces are corrected by that delta.
* opening the web UI will compare rayhunter's current time with the web client's current time, and update the delta if the time is off by more than 1 minute. probably configurable, with confirmation, etc. 1 minute because small drifts are permissible and preferrable over timestamps jumping around in PCAPs

So there's no need to support setting the system time per-device or figuring out permissions.

NTP support can be added, but from what i understand this is only an issue on devices that have no activated SIM card and therefore no network connection?

**Comment by MatejKovacic** [comment]
Not really. A friend of mine is using Rayhunter on TPLink, he is using active and valid SIM card and time is still not set.

**Comment by MatejKovacic** [comment]
Ah, we found out what was the problem. When yoi turn on the device, time is set to initial Unix time (1.1.1970). So WebUI will show that as beginning of a capture. 

Of course, if you download PCAP file, you will be able to see NTP packet and time change, but in WebUI, start time stays the same.

So yes, we should wait to get actual time from the capture (or even parse NTP packet by ourselves) and then compute time delta and update information about current capture.

**Comment by untitaker** [comment]
> So WebUI will show that as beginning of a capture.

so for you that's the only glitch, the current time is eventually correct after start?

**Comment by MatejKovacic** [comment]
I think there are two things. One is to correct time in webUI. And another is to get time info if network does not push NTP info to the device.

And maybe to set the time via web browser for those who do not have SIM card inserted.

**Comment by OboTheHobo** [comment]
For those looking for a workaround; idk why permissions still get denied if you run `/bin/rootshell` through `adb shell`, but it does work if you use the installer and run `./installer utils orbic-shell --admin-password [password]` . Then you can run `rootshell` and then the date command to set the date
