### ISSUE TITLE
Rayhunter stops after deleting an entry

### ISSUE THREAD

**Issue by S-cpu3** [EFForg/rayhunter#433]
### Bug Report Details

- **Rayhunter Verison**: v0.3.4
- **Capture date**: 2025-06-27
-  **Device and Model**: Verizon Orbic hotspot 
- **What happened**: After plugging in Rayhunter via USB and running the "adb forward tcp:8080 tcp:8080" command, if i delete a file entry which was captured by Rayhunter, Rayhunter appears to stop and must be manually restarted. The orbic line also goes from green to white. 

- **Step 1**: Plug in Orbic hotspot into your computer via USB. 
- **Step 2**: Open your terminal or Command prompt and paste the command "adb forward tcp:8080 tcp:8080" 
- **Step 3**: Open web browser and type in localhost:8080 into the URL bar and hit enter 
- **Step 4**: Select a entry to delete and confirm that deletion. 
- **Step 5**: Rayhunter should now have an error saying it is no longer running 

![Image](https://github.com/user-attachments/assets/72cc923b-da12-4bd3-923a-bf1f736d6044)

**Expected behavior**: Rayhunter should still be running despite file deletion.

**Comment by gaykitty** [comment]
Are you deleting the currently recording capture or an older one?

**Comment by S-cpu3** [comment]
> Are you deleting the currently recording capture or an older one?

I am deleting an older capture.

**Comment by MatejKovacic** [comment]
Have you tried with with 0.4.0 release? I think this bug was already resolved with new release...

**Comment by S-cpu3** [comment]
> Have you tried with with 0.4.0 release? I think this bug was already resolved with new release...

I have tried with 0.4.0 release and it is still the same issue.

**Comment by S-cpu3** [comment]
Deleting an older entry still results in a pause

**Comment by cooperq** [comment]
I can reproduce this, I think this is maybe something @untitaker implemented but I can't remember why. Is this still necessary even on old recordings? It's not an ideal user experience.

**Comment by untitaker** [comment]
I think it might have been like this from the start. I only fixed some crashes. code seems pretty clear in that it implements the observed behavior: https://github.com/efforg/rayhunter/blob/652488226a2b6efeacf3a12d54665e03ad3e324b/bin/src/qmdl_store.rs#L283-L289

**Comment by gaykitty** [comment]
Unless I'm miss reading that, it's only stopping the recording if the user is deleting the current recording. When I have my Orbic in front of my I'll poke at this more.

**Comment by untitaker** [comment]
ah yeah my bad 👍

**Comment by gaykitty** [comment]
@untitaker you were right, this was my bug, but it was this code not being conditioned on the current recording being the one being deleted https://github.com/EFForg/rayhunter/blob/652488226a2b6efeacf3a12d54665e03ad3e324b/bin/src/diag.rs#L222-L241
